// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inline_album.sql

package database

import (
	"context"
)

const getInlineAlbumPayload = `-- name: GetInlineAlbumPayload :one
SELECT hash, extractor_id, content_id, created_at
FROM inline_album_payload
WHERE hash = $1
`

func (q *Queries) GetInlineAlbumPayload(ctx context.Context, hash string) (InlineAlbumPayload, error) {
	row := q.db.QueryRow(ctx, getInlineAlbumPayload, hash)
	var i InlineAlbumPayload
	err := row.Scan(
		&i.Hash,
		&i.ExtractorID,
		&i.ContentID,
		&i.CreatedAt,
	)
	return i, err
}

const getInlineAlbumRef = `-- name: GetInlineAlbumRef :one
SELECT user_id, extractor_id, content_id, message_id, created_at
FROM inline_album_ref
WHERE user_id = $1
  AND extractor_id = $2
  AND content_id = $3
`

type GetInlineAlbumRefParams struct {
	UserID      int64
	ExtractorID string
	ContentID   string
}

func (q *Queries) GetInlineAlbumRef(ctx context.Context, arg GetInlineAlbumRefParams) (InlineAlbumRef, error) {
	row := q.db.QueryRow(ctx, getInlineAlbumRef, arg.UserID, arg.ExtractorID, arg.ContentID)
	var i InlineAlbumRef
	err := row.Scan(
		&i.UserID,
		&i.ExtractorID,
		&i.ContentID,
		&i.MessageID,
		&i.CreatedAt,
	)
	return i, err
}

const upsertInlineAlbumPayload = `-- name: UpsertInlineAlbumPayload :exec
INSERT INTO inline_album_payload (hash, extractor_id, content_id)
VALUES ($1, $2, $3)
ON CONFLICT (hash) DO UPDATE
SET extractor_id = EXCLUDED.extractor_id,
    content_id = EXCLUDED.content_id
`

type UpsertInlineAlbumPayloadParams struct {
	Hash        string
	ExtractorID string
	ContentID   string
}

func (q *Queries) UpsertInlineAlbumPayload(ctx context.Context, arg UpsertInlineAlbumPayloadParams) error {
	_, err := q.db.Exec(ctx, upsertInlineAlbumPayload, arg.Hash, arg.ExtractorID, arg.ContentID)
	return err
}

const upsertInlineAlbumRef = `-- name: UpsertInlineAlbumRef :exec
INSERT INTO inline_album_ref (user_id, extractor_id, content_id, message_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, extractor_id, content_id) DO UPDATE
SET message_id = EXCLUDED.message_id,
    created_at = CURRENT_TIMESTAMP
`

type UpsertInlineAlbumRefParams struct {
	UserID      int64
	ExtractorID string
	ContentID   string
	MessageID   int64
}

func (q *Queries) UpsertInlineAlbumRef(ctx context.Context, arg UpsertInlineAlbumRefParams) error {
	_, err := q.db.Exec(ctx, upsertInlineAlbumRef,
		arg.UserID,
		arg.ExtractorID,
		arg.ContentID,
		arg.MessageID,
	)
	return err
}
